"""Generate the PDF CV bibliography from the same records used by the website.

Run from any directory: python scripts/build_cv_publications.py
Requires PyYAML. Then compile CV_latex/CV_XiayuZhao.tex with pdflatex.
"""
from pathlib import Path
import re
import yaml

ROOT=Path(__file__).resolve().parents[1]

def escape(value):
    value=str(value).replace('—','---').replace('–','--').replace('’',"'")
    replacements={'\\':r'\textbackslash{}','&':r'\&','%':r'\%','$':r'\$','#':r'\#','_':r'\_','{':r'\{','}':r'\}','~':r'\textasciitilde{}','^':r'\textasciicircum{}'}
    return ''.join(replacements.get(c,c) for c in value)

def authors(names):
    values=[]
    for name in names[:8]:
        parts=name.split()
        short=escape(parts[-1]+', '+' '.join(p[0]+'.' for p in parts[:-1]))
        values.append(r'\textbf{'+short+'}' if name=='Xiayu Zhao' else short)
    return ', '.join(values)+(', et al.' if len(names)>8 else '')

records=[]
for path in (ROOT/'_publications').glob('*.md'):
    record=yaml.safe_load(path.read_text(encoding='utf-8').split('---',2)[1])
    if record.get('scholar_id'): records.append(record)
records.sort(key=lambda r:(str(r['date']),r['title']),reverse=True)
lines=[r'% Generated by scripts/build_cv_publications.py; edit _publications/*.md instead.',
    r'\noindent\textit{Publication records checked against Google Scholar, September 2026.}',
    r'\par\smallskip\noindent\textit{Two similar 2021 Scholar records are retained under their listed English titles and may refer to the same article.}', '']
for index,(category,heading) in enumerate([('manuscripts','Journal Articles'),('conferences','Conference Papers')]):
    lines += [r'\subsection*{'+heading+'}',r'\begin{enumerate}[leftmargin=1.5em'+(', resume' if index else '')+']']
    for r in records:
        if r['category']!=category: continue
        vol=str(r.get('volume',''))+(f"({r['issue']})" if r.get('issue') else '')
        tail=', '.join(str(v) for v in [vol,r.get('pages','')] if v)
        lines.append(r'\item '+authors(r['authors'])+' ('+str(r['date'])[:4]+'). ``'+escape(r['title'])+r".'' \textit{"+escape(r['venue'])+'}'+(', '+escape(tail) if tail else '')+'. '+r'\href{'+r['paperurl']+r'}{Paper}.')
    lines += [r'\end{enumerate}', '']
(ROOT/'CV_latex/publications.tex').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(f'Generated CV bibliography: {len(records)} Scholar records.')
